"""Add subtopic

Revision ID: 644f9a565477
Revises: 
Create Date: 2026-05-16 14:04:39.037729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644f9a565477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtopic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('subtopic')

    # ### end Alembic commands ###
